version: '3'

services:

  rabbitmq1:
    image: rabbitmq:${RABBITMQ_DOCKER_TAG}
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes: 
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./config/advanced.config:/etc/rabbitmq/advanced.config
      - ./config/enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
       - 5673:5672
       - 15673:15672

  rabbitmq2:
    image: rabbitmq:${RABBITMQ_DOCKER_TAG}
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./config/advanced.config:/etc/rabbitmq/advanced.config
      - ./config/enabled_plugins:/etc/rabbitmq/enabled_plugins
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    ports:
       - 5674:5672
       - 15674:15672

  rabbitmq3:
    image: rabbitmq:${RABBITMQ_DOCKER_TAG}
    hostname: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./config/advanced.config:/etc/rabbitmq/advanced.config
      - ./config/enabled_plugins:/etc/rabbitmq/enabled_plugins
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    ports:
       - 5675:5672
       - 15675:15672
    
  haproxy:
    image: haproxy:1.7
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 15672:15672
      - 5672:5672
